name: ShaderAPI
main: com.liamxsage.shaderapi.ShaderAPI
version: ${version}
description: "This is a plugin for PaperSpigot that allows you to apply shaders to your Minecraft players."
author: "LiamXSage"
api-version: "1.21"
loader: com.liamxsage.shaderapi.DependencyLoader